### ISSUE TITLE
[Feature Request] Ordered Representation of Maps

### ISSUE THREAD

**Issue by daidoji** [scalpel-software/cbor#5]
We have a project that requires an ordered representation of a map (for cryptographic signing purposes) and not the unordered map type represented on the BEAM.  It would be nice if this library supported something like `Jason.OrderedObject` (for JSON) representation or `erlang-msgpack`'s ability to deserialize into jsx or jiffy proplists.

**Comment by tomciopp** [comment]
@daidoji Always glad to hear from people using the library!

Are you running into this issue when trying to encode or decode objects?

**Comment by daidoji** [comment]
Well we haven't run into this issue but our BEAM tests do show that %{} representations don't respect the order of things serialized/deserialized off the wire and we couldn't figure out a way to get this library to respect that (artificial) requirement we have for a cbor library.  Is there a way to extract the ordered representation from a cbor serialization/write an ordered representation to the wire?

**Comment by tomciopp** [comment]
So since maps do not guarantee sort order in elixir/erlang by serializing the a map in cbor you're not going to have any guarantees of a certain order when putting it to the wire. You can however add an additional layer of indirection on top of cbor for whatever data structure you're trying to encode in one of two ways. 

You can implement the protocol of something like Jason.OrderedObject directly in one of two ways. 

```elixir
defimpl CBOR.Encoder, for: Jason.OrderedObject do
  def encode_into(map, acc) when map_size(map) == 0, do: <<acc::binary, 0xa0>>

  def encode_into(map, acc) when map_size(map) < 0x10000000000000000 do
    Enum.reduce(map, CBOR.Utils.encode_head(5, map_size(map), acc), fn({k, v}, subacc) ->
      CBOR.Encoder.encode_into(v, CBOR.Encoder.encode_into(k, subacc))
    end)
  end

  def encode_into(map, acc) do
    Enum.reduce(map, <<acc::binary, 0xbf>>, fn({k, v}, subacc) ->
      CBOR.Encoder.encode_into(v, CBOR.Encoder.encode_into(k, subacc))
    end) <> <<0xff>>
  end
end
```

The above code is using the same implementation as the internal `Map` but since `Jason.OrderedObject` preserves sort order for the `Access` module, the order will be preserved. However in this case it will be still considered a map so on deserialization you're just going to get a vanilla map.

Your second options would be to create a custom wrapper around a `%CBOR.Tag{}`. When you encode something that is semantically different than the standard data structures listed in the RFC this should likely be your go to method. When decoding there's no ability to explicitly say automatically decode into this new data structure that I've defined. However what you can do is create a separate module that converts your data into a `%CBOR.Tag{tag: :bytes, value: your_data_here}` so that when you're decoding you can see that this is different and run an additional step to convert it to structure you need.

This is the boundary point that the protocol itself has defined and any special modifications are up to the reader to implement. If you have any additional questions I'd be happy to try to point you in the right direction, but I hope you can understand why it doesn't make sense for this library to determine exact use cases for undetermined functionality as it's likely that a single implementation will cause incompatible results for different users.

**Comment by daidoji** [comment]
We're trying to implement [a cryptographic protocol](https://github.com/trustoverip/tswg-cesr-specification/) and this dependency that we serialized into an ordered representation and deserialize into an ordered representation is forced on us from outside unfortunately.  We don't have any control over that.  The requirements are dictated by the choice of python in the reference implementation for the most part with which we'd like to be compatible.

The Encoder code you pasted should work for us for writing to the wire.  Would a similar trick work for reading from the wire?  

Tags unfortunately won't work as they'll change the byte structure of the payload itself.  As we'll eventually have to sign these data structures that will cause issues of signatures between implementations.

**Comment by tomciopp** [comment]
As written, that decoder will decode into a regular map if using this library. Other languages may be different in their implementation and data structures with respect to ordering. You _could_ write a custom decoder that used an ordered map if that's all you're going to need. Here are the lines you would need to change in the decoder, just replace any instance of the map will the data structure of your choice. There's not really an option for hooks into decoding as of right now.

https://github.com/scalpel-software/cbor/blob/master/lib/cbor/decoder.ex#L85-L100

**Comment by daidoji** [comment]
Would you accept a PR for that or did you mean in a private fork?  Glad to help out future generations who might need this.

**Comment by tomciopp** [comment]
My instinct would be to start with a private fork, and if you're willing to share I'd be happy to review it and possibly merge it in. There has been a new RFC that supposedly supersedes the first version of CBOR so I may need to take a look at that and do some maintenance anyway. 

My first thought would be to add an additional options list that would accept a custom decoder function that we would call instead of the default behavior. An API like `CBOR.decode(binary, map: CustomMapDecoder)` makes sense to me, but it will do this for _all._ maps, you have no ability to pick and choose. Let me do some reading and get back to you.

**Comment by daidoji** [comment]
Yeah the new RFC doesn't mention what we're looking for particularly.  We'll hack around on it and if we come up with something reasonable we can show it to you and you can decide.  

We don't mind not picking and choosing, in our cryptographic context we'd actually like to impose an order on all data elements so we're fine with a CBOR map -> property list (whcih is essentially what Jason.OrderedObject is).  We used erlang-messagpack and they do messagepack maps -> jsx/jiffy serializations in much the same manner.
